// flow-typed signature: 99e2e02cbf20e7da05563278a2541c5c
// flow-typed version: <<STUB>>/babel-plugin-inferno_v1.4.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-inferno'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-inferno' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-inferno/example' {
  declare module.exports: any;
}

declare module 'babel-plugin-inferno/lib/attrsSVG' {
  declare module.exports: any;
}

declare module 'babel-plugin-inferno/lib/flags' {
  declare module.exports: any;
}

declare module 'babel-plugin-inferno/lib/helpers/flatten-expressions' {
  declare module.exports: any;
}

declare module 'babel-plugin-inferno/lib/helpers/is-array' {
  declare module.exports: any;
}

declare module 'babel-plugin-inferno/lib/helpers/is-component' {
  declare module.exports: any;
}

declare module 'babel-plugin-inferno/lib/helpers/is-null-or-undefined' {
  declare module.exports: any;
}

declare module 'babel-plugin-inferno/lib/helpers/to-expression' {
  declare module.exports: any;
}

declare module 'babel-plugin-inferno/lib/helpers/to-reference' {
  declare module.exports: any;
}

declare module 'babel-plugin-inferno/lib/helpers/to-statement' {
  declare module.exports: any;
}

declare module 'babel-plugin-inferno/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-inferno/example.js' {
  declare module.exports: $Exports<'babel-plugin-inferno/example'>;
}
declare module 'babel-plugin-inferno/lib/attrsSVG.js' {
  declare module.exports: $Exports<'babel-plugin-inferno/lib/attrsSVG'>;
}
declare module 'babel-plugin-inferno/lib/flags.js' {
  declare module.exports: $Exports<'babel-plugin-inferno/lib/flags'>;
}
declare module 'babel-plugin-inferno/lib/helpers/flatten-expressions.js' {
  declare module.exports: $Exports<'babel-plugin-inferno/lib/helpers/flatten-expressions'>;
}
declare module 'babel-plugin-inferno/lib/helpers/is-array.js' {
  declare module.exports: $Exports<'babel-plugin-inferno/lib/helpers/is-array'>;
}
declare module 'babel-plugin-inferno/lib/helpers/is-component.js' {
  declare module.exports: $Exports<'babel-plugin-inferno/lib/helpers/is-component'>;
}
declare module 'babel-plugin-inferno/lib/helpers/is-null-or-undefined.js' {
  declare module.exports: $Exports<'babel-plugin-inferno/lib/helpers/is-null-or-undefined'>;
}
declare module 'babel-plugin-inferno/lib/helpers/to-expression.js' {
  declare module.exports: $Exports<'babel-plugin-inferno/lib/helpers/to-expression'>;
}
declare module 'babel-plugin-inferno/lib/helpers/to-reference.js' {
  declare module.exports: $Exports<'babel-plugin-inferno/lib/helpers/to-reference'>;
}
declare module 'babel-plugin-inferno/lib/helpers/to-statement.js' {
  declare module.exports: $Exports<'babel-plugin-inferno/lib/helpers/to-statement'>;
}
declare module 'babel-plugin-inferno/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-inferno/lib/index'>;
}
