// flow-typed signature: 4aa6df454dc2244ad0e3c719d3b69c23
// flow-typed version: <<STUB>>/babel-preset-flow-tcomb-forked_v^1.3.3/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-flow-tcomb-forked'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-flow-tcomb-forked' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-flow-tcomb-forked/index' {
  declare module.exports: $Exports<'babel-preset-flow-tcomb-forked'>;
}
declare module 'babel-preset-flow-tcomb-forked/index.js' {
  declare module.exports: $Exports<'babel-preset-flow-tcomb-forked'>;
}
