// flow-typed signature: 59f96834fa27b48139d8651b04b6b4f9
// flow-typed version: <<STUB>>/eslint-plugin-smells_v^1.0.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-smells'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-smells' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-smells/lib/rules/no-complex-chaining' {
  declare module.exports: any;
}

declare module 'eslint-plugin-smells/lib/rules/no-complex-string-concat' {
  declare module.exports: any;
}

declare module 'eslint-plugin-smells/lib/rules/no-complex-switch-case' {
  declare module.exports: any;
}

declare module 'eslint-plugin-smells/lib/rules/no-setinterval' {
  declare module.exports: any;
}

declare module 'eslint-plugin-smells/lib/rules/no-switch' {
  declare module.exports: any;
}

declare module 'eslint-plugin-smells/lib/rules/no-this-assign' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-smells/index' {
  declare module.exports: $Exports<'eslint-plugin-smells'>;
}
declare module 'eslint-plugin-smells/index.js' {
  declare module.exports: $Exports<'eslint-plugin-smells'>;
}
declare module 'eslint-plugin-smells/lib/rules/no-complex-chaining.js' {
  declare module.exports: $Exports<'eslint-plugin-smells/lib/rules/no-complex-chaining'>;
}
declare module 'eslint-plugin-smells/lib/rules/no-complex-string-concat.js' {
  declare module.exports: $Exports<'eslint-plugin-smells/lib/rules/no-complex-string-concat'>;
}
declare module 'eslint-plugin-smells/lib/rules/no-complex-switch-case.js' {
  declare module.exports: $Exports<'eslint-plugin-smells/lib/rules/no-complex-switch-case'>;
}
declare module 'eslint-plugin-smells/lib/rules/no-setinterval.js' {
  declare module.exports: $Exports<'eslint-plugin-smells/lib/rules/no-setinterval'>;
}
declare module 'eslint-plugin-smells/lib/rules/no-switch.js' {
  declare module.exports: $Exports<'eslint-plugin-smells/lib/rules/no-switch'>;
}
declare module 'eslint-plugin-smells/lib/rules/no-this-assign.js' {
  declare module.exports: $Exports<'eslint-plugin-smells/lib/rules/no-this-assign'>;
}
