// flow-typed signature: 2808b9dab32bf241ea7854e039ccdd78
// flow-typed version: <<STUB>>/http-hash_v^2.0.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'http-hash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'http-hash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'http-hash/examples/example1' {
  declare module.exports: any;
}

declare module 'http-hash/examples/example2' {
  declare module.exports: any;
}

declare module 'http-hash/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'http-hash/examples/example1.js' {
  declare module.exports: $Exports<'http-hash/examples/example1'>;
}
declare module 'http-hash/examples/example2.js' {
  declare module.exports: $Exports<'http-hash/examples/example2'>;
}
declare module 'http-hash/index' {
  declare module.exports: $Exports<'http-hash'>;
}
declare module 'http-hash/index.js' {
  declare module.exports: $Exports<'http-hash'>;
}
declare module 'http-hash/test/index.js' {
  declare module.exports: $Exports<'http-hash/test/index'>;
}
