// flow-typed signature: b1fe3e279139b809362b8fabee648a93
// flow-typed version: <<STUB>>/inferno-create-class_v^1.0.7/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inferno-create-class'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'inferno-create-class' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inferno-create-class/inferno-create-class' {
  declare module.exports: any;
}

declare module 'inferno-create-class/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inferno-create-class/inferno-create-class.js' {
  declare module.exports: $Exports<'inferno-create-class/inferno-create-class'>;
}
declare module 'inferno-create-class/src/index.js' {
  declare module.exports: $Exports<'inferno-create-class/src/index'>;
}
