// flow-typed signature: d8886e06b5b2a9b00d5480791a16fdaa
// flow-typed version: <<STUB>>/inferno_v^1.0.2/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inferno'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'inferno' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inferno/dist/inferno-compat' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-component' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-create-class' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-create-element' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-devtools' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-hyperscript' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-mobx' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-redux' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-router' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-server' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-test-utils' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-vnode-flags' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno' {
  declare module.exports: any;
}

declare module 'inferno/inferno' {
  declare module.exports: any;
}

declare module 'inferno/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inferno/dist/inferno-compat.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-compat'>;
}
declare module 'inferno/dist/inferno-component.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-component'>;
}
declare module 'inferno/dist/inferno-create-class.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-create-class'>;
}
declare module 'inferno/dist/inferno-create-element.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-create-element'>;
}
declare module 'inferno/dist/inferno-devtools.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-devtools'>;
}
declare module 'inferno/dist/inferno-hyperscript.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-hyperscript'>;
}
declare module 'inferno/dist/inferno-mobx.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-mobx'>;
}
declare module 'inferno/dist/inferno-redux.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-redux'>;
}
declare module 'inferno/dist/inferno-router.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-router'>;
}
declare module 'inferno/dist/inferno-server.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-server'>;
}
declare module 'inferno/dist/inferno-test-utils.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-test-utils'>;
}
declare module 'inferno/dist/inferno-vnode-flags.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-vnode-flags'>;
}
declare module 'inferno/dist/inferno.js' {
  declare module.exports: $Exports<'inferno/dist/inferno'>;
}
declare module 'inferno/inferno.js' {
  declare module.exports: $Exports<'inferno/inferno'>;
}
declare module 'inferno/src/index.js' {
  declare module.exports: $Exports<'inferno/src/index'>;
}
