// flow-typed signature: fabb22dfc6f98df85894586a10d2e06e
// flow-typed version: <<STUB>>/inferno-devtools_v^1.0.2/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inferno-devtools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'inferno-devtools' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inferno-devtools/inferno-devtools' {
  declare module.exports: any;
}

declare module 'inferno-devtools/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inferno-devtools/inferno-devtools.js' {
  declare module.exports: $Exports<'inferno-devtools/inferno-devtools'>;
}
declare module 'inferno-devtools/src/index.js' {
  declare module.exports: $Exports<'inferno-devtools/src/index'>;
}
