// flow-typed signature: 5d06afbc3eb95918626cd173d1056e2c
// flow-typed version: <<STUB>>/inferno_v^1.1.2/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inferno'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'inferno' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inferno/dist/inferno-compat' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-compat.min' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-compat.node' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-component' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-component.min' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-component.node' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-create-class' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-create-class.min' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-create-class.node' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-create-element' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-create-element.min' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-create-element.node' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-devtools' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-devtools.min' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-devtools.node' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-hyperscript' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-hyperscript.min' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-hyperscript.node' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-mobx' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-mobx.min' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-mobx.node' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-redux' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-redux.min' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-redux.node' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-router' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-router.min' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-router.node' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-server' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-server.min' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-server.node' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-test-utils' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-test-utils.min' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-test-utils.node' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-vnode-flags' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-vnode-flags.min' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno-vnode-flags.node' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno.min' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno.node' {
  declare module.exports: any;
}

declare module 'inferno/inferno' {
  declare module.exports: any;
}

declare module 'inferno/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inferno/dist/inferno-compat.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-compat'>;
}
declare module 'inferno/dist/inferno-compat.min.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-compat.min'>;
}
declare module 'inferno/dist/inferno-compat.node.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-compat.node'>;
}
declare module 'inferno/dist/inferno-component.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-component'>;
}
declare module 'inferno/dist/inferno-component.min.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-component.min'>;
}
declare module 'inferno/dist/inferno-component.node.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-component.node'>;
}
declare module 'inferno/dist/inferno-create-class.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-create-class'>;
}
declare module 'inferno/dist/inferno-create-class.min.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-create-class.min'>;
}
declare module 'inferno/dist/inferno-create-class.node.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-create-class.node'>;
}
declare module 'inferno/dist/inferno-create-element.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-create-element'>;
}
declare module 'inferno/dist/inferno-create-element.min.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-create-element.min'>;
}
declare module 'inferno/dist/inferno-create-element.node.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-create-element.node'>;
}
declare module 'inferno/dist/inferno-devtools.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-devtools'>;
}
declare module 'inferno/dist/inferno-devtools.min.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-devtools.min'>;
}
declare module 'inferno/dist/inferno-devtools.node.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-devtools.node'>;
}
declare module 'inferno/dist/inferno-hyperscript.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-hyperscript'>;
}
declare module 'inferno/dist/inferno-hyperscript.min.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-hyperscript.min'>;
}
declare module 'inferno/dist/inferno-hyperscript.node.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-hyperscript.node'>;
}
declare module 'inferno/dist/inferno-mobx.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-mobx'>;
}
declare module 'inferno/dist/inferno-mobx.min.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-mobx.min'>;
}
declare module 'inferno/dist/inferno-mobx.node.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-mobx.node'>;
}
declare module 'inferno/dist/inferno-redux.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-redux'>;
}
declare module 'inferno/dist/inferno-redux.min.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-redux.min'>;
}
declare module 'inferno/dist/inferno-redux.node.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-redux.node'>;
}
declare module 'inferno/dist/inferno-router.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-router'>;
}
declare module 'inferno/dist/inferno-router.min.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-router.min'>;
}
declare module 'inferno/dist/inferno-router.node.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-router.node'>;
}
declare module 'inferno/dist/inferno-server.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-server'>;
}
declare module 'inferno/dist/inferno-server.min.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-server.min'>;
}
declare module 'inferno/dist/inferno-server.node.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-server.node'>;
}
declare module 'inferno/dist/inferno-test-utils.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-test-utils'>;
}
declare module 'inferno/dist/inferno-test-utils.min.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-test-utils.min'>;
}
declare module 'inferno/dist/inferno-test-utils.node.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-test-utils.node'>;
}
declare module 'inferno/dist/inferno-vnode-flags.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-vnode-flags'>;
}
declare module 'inferno/dist/inferno-vnode-flags.min.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-vnode-flags.min'>;
}
declare module 'inferno/dist/inferno-vnode-flags.node.js' {
  declare module.exports: $Exports<'inferno/dist/inferno-vnode-flags.node'>;
}
declare module 'inferno/dist/inferno.js' {
  declare module.exports: $Exports<'inferno/dist/inferno'>;
}
declare module 'inferno/dist/inferno.min.js' {
  declare module.exports: $Exports<'inferno/dist/inferno.min'>;
}
declare module 'inferno/dist/inferno.node.js' {
  declare module.exports: $Exports<'inferno/dist/inferno.node'>;
}
declare module 'inferno/inferno.js' {
  declare module.exports: $Exports<'inferno/inferno'>;
}
declare module 'inferno/src/index.js' {
  declare module.exports: $Exports<'inferno/src/index'>;
}
