// flow-typed signature: 5c3e3a64e7ebd6cd7c5cf19684c462d9
// flow-typed version: <<STUB>>/inferno-create-element_v^1.0.2/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inferno-create-element'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'inferno-create-element' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inferno-create-element/inferno-create-element' {
  declare module.exports: any;
}

declare module 'inferno-create-element/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inferno-create-element/inferno-create-element.js' {
  declare module.exports: $Exports<'inferno-create-element/inferno-create-element'>;
}
declare module 'inferno-create-element/src/index.js' {
  declare module.exports: $Exports<'inferno-create-element/src/index'>;
}
