// flow-typed signature: c5c479f82d6a504073a5d35627bded18
// flow-typed version: <<STUB>>/inferno-mobx_v^1.1.2/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inferno-mobx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'inferno-mobx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inferno-mobx/inferno-mobx' {
  declare module.exports: any;
}

declare module 'inferno-mobx/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inferno-mobx/inferno-mobx.js' {
  declare module.exports: $Exports<'inferno-mobx/inferno-mobx'>;
}
declare module 'inferno-mobx/src/index.js' {
  declare module.exports: $Exports<'inferno-mobx/src/index'>;
}
