// flow-typed signature: 518b6aee427d986033beeb8d027d218a
// flow-typed version: <<STUB>>/isparta-loader_v^2.0.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'isparta-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'isparta-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'isparta-loader/index' {
  declare module.exports: $Exports<'isparta-loader'>;
}
declare module 'isparta-loader/index.js' {
  declare module.exports: $Exports<'isparta-loader'>;
}
