// flow-typed signature: bcbce9c4858686191316550efe3f8e83
// flow-typed version: <<STUB>>/jsinspect_v^0.8.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsinspect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsinspect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsinspect/lib/inspector' {
  declare module.exports: any;
}

declare module 'jsinspect/lib/match' {
  declare module.exports: any;
}

declare module 'jsinspect/lib/nodeUtils' {
  declare module.exports: any;
}

declare module 'jsinspect/lib/reporters/base' {
  declare module.exports: any;
}

declare module 'jsinspect/lib/reporters/default' {
  declare module.exports: any;
}

declare module 'jsinspect/lib/reporters/index' {
  declare module.exports: any;
}

declare module 'jsinspect/lib/reporters/json' {
  declare module.exports: any;
}

declare module 'jsinspect/lib/reporters/pmd' {
  declare module.exports: any;
}

declare module 'jsinspect/spec/fixtures/amd' {
  declare module.exports: any;
}

declare module 'jsinspect/spec/fixtures/commonjs' {
  declare module.exports: any;
}

declare module 'jsinspect/spec/fixtures/es6Module' {
  declare module.exports: any;
}

declare module 'jsinspect/spec/fixtures/identifiers' {
  declare module.exports: any;
}

declare module 'jsinspect/spec/fixtures/indentation' {
  declare module.exports: any;
}

declare module 'jsinspect/spec/fixtures/index' {
  declare module.exports: any;
}

declare module 'jsinspect/spec/fixtures/intersection' {
  declare module.exports: any;
}

declare module 'jsinspect/spec/fixtures/redundantIntersection' {
  declare module.exports: any;
}

declare module 'jsinspect/spec/fixtures/simple' {
  declare module.exports: any;
}

declare module 'jsinspect/spec/fixtures/smallDiffs' {
  declare module.exports: any;
}

declare module 'jsinspect/spec/helpers' {
  declare module.exports: any;
}

declare module 'jsinspect/spec/inspectorSpec' {
  declare module.exports: any;
}

declare module 'jsinspect/spec/matchSpec' {
  declare module.exports: any;
}

declare module 'jsinspect/spec/nodeUtilsSpec' {
  declare module.exports: any;
}

declare module 'jsinspect/spec/reporters/baseSpec' {
  declare module.exports: any;
}

declare module 'jsinspect/spec/reporters/defaultSpec' {
  declare module.exports: any;
}

declare module 'jsinspect/spec/reporters/jsonSpec' {
  declare module.exports: any;
}

declare module 'jsinspect/spec/reporters/pmdSpec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsinspect/lib/inspector.js' {
  declare module.exports: $Exports<'jsinspect/lib/inspector'>;
}
declare module 'jsinspect/lib/match.js' {
  declare module.exports: $Exports<'jsinspect/lib/match'>;
}
declare module 'jsinspect/lib/nodeUtils.js' {
  declare module.exports: $Exports<'jsinspect/lib/nodeUtils'>;
}
declare module 'jsinspect/lib/reporters/base.js' {
  declare module.exports: $Exports<'jsinspect/lib/reporters/base'>;
}
declare module 'jsinspect/lib/reporters/default.js' {
  declare module.exports: $Exports<'jsinspect/lib/reporters/default'>;
}
declare module 'jsinspect/lib/reporters/index.js' {
  declare module.exports: $Exports<'jsinspect/lib/reporters/index'>;
}
declare module 'jsinspect/lib/reporters/json.js' {
  declare module.exports: $Exports<'jsinspect/lib/reporters/json'>;
}
declare module 'jsinspect/lib/reporters/pmd.js' {
  declare module.exports: $Exports<'jsinspect/lib/reporters/pmd'>;
}
declare module 'jsinspect/spec/fixtures/amd.js' {
  declare module.exports: $Exports<'jsinspect/spec/fixtures/amd'>;
}
declare module 'jsinspect/spec/fixtures/commonjs.js' {
  declare module.exports: $Exports<'jsinspect/spec/fixtures/commonjs'>;
}
declare module 'jsinspect/spec/fixtures/es6Module.js' {
  declare module.exports: $Exports<'jsinspect/spec/fixtures/es6Module'>;
}
declare module 'jsinspect/spec/fixtures/identifiers.js' {
  declare module.exports: $Exports<'jsinspect/spec/fixtures/identifiers'>;
}
declare module 'jsinspect/spec/fixtures/indentation.js' {
  declare module.exports: $Exports<'jsinspect/spec/fixtures/indentation'>;
}
declare module 'jsinspect/spec/fixtures/index.js' {
  declare module.exports: $Exports<'jsinspect/spec/fixtures/index'>;
}
declare module 'jsinspect/spec/fixtures/intersection.js' {
  declare module.exports: $Exports<'jsinspect/spec/fixtures/intersection'>;
}
declare module 'jsinspect/spec/fixtures/redundantIntersection.js' {
  declare module.exports: $Exports<'jsinspect/spec/fixtures/redundantIntersection'>;
}
declare module 'jsinspect/spec/fixtures/simple.js' {
  declare module.exports: $Exports<'jsinspect/spec/fixtures/simple'>;
}
declare module 'jsinspect/spec/fixtures/smallDiffs.js' {
  declare module.exports: $Exports<'jsinspect/spec/fixtures/smallDiffs'>;
}
declare module 'jsinspect/spec/helpers.js' {
  declare module.exports: $Exports<'jsinspect/spec/helpers'>;
}
declare module 'jsinspect/spec/inspectorSpec.js' {
  declare module.exports: $Exports<'jsinspect/spec/inspectorSpec'>;
}
declare module 'jsinspect/spec/matchSpec.js' {
  declare module.exports: $Exports<'jsinspect/spec/matchSpec'>;
}
declare module 'jsinspect/spec/nodeUtilsSpec.js' {
  declare module.exports: $Exports<'jsinspect/spec/nodeUtilsSpec'>;
}
declare module 'jsinspect/spec/reporters/baseSpec.js' {
  declare module.exports: $Exports<'jsinspect/spec/reporters/baseSpec'>;
}
declare module 'jsinspect/spec/reporters/defaultSpec.js' {
  declare module.exports: $Exports<'jsinspect/spec/reporters/defaultSpec'>;
}
declare module 'jsinspect/spec/reporters/jsonSpec.js' {
  declare module.exports: $Exports<'jsinspect/spec/reporters/jsonSpec'>;
}
declare module 'jsinspect/spec/reporters/pmdSpec.js' {
  declare module.exports: $Exports<'jsinspect/spec/reporters/pmdSpec'>;
}
