// flow-typed signature: 5e1fa1b0a3ce7396a4f8091670a1391b
// flow-typed version: <<STUB>>/mobx-logger_v^0.3.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mobx-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mobx-logger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mobx-logger/lib/index' {
  declare module.exports: any;
}

declare module 'mobx-logger/lib/log' {
  declare module.exports: any;
}

declare module 'mobx-logger/lib/utils' {
  declare module.exports: any;
}

declare module 'mobx-logger/mobx-logger.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mobx-logger/lib/index.js' {
  declare module.exports: $Exports<'mobx-logger/lib/index'>;
}
declare module 'mobx-logger/lib/log.js' {
  declare module.exports: $Exports<'mobx-logger/lib/log'>;
}
declare module 'mobx-logger/lib/utils.js' {
  declare module.exports: $Exports<'mobx-logger/lib/utils'>;
}
declare module 'mobx-logger/mobx-logger.umd.js' {
  declare module.exports: $Exports<'mobx-logger/mobx-logger.umd'>;
}
