// flow-typed signature: 875314b1b95fe6170a158b4b4008d49f
// flow-typed version: <<STUB>>/mobx-remotedev_v^0.2.4/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mobx-remotedev'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mobx-remotedev' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mobx-remotedev/dist/mobx-remotedev' {
  declare module.exports: any;
}

declare module 'mobx-remotedev/dist/mobx-remotedev.min' {
  declare module.exports: any;
}

declare module 'mobx-remotedev/lib/dev' {
  declare module.exports: any;
}

declare module 'mobx-remotedev/lib/filters' {
  declare module.exports: any;
}

declare module 'mobx-remotedev/lib/getDecorator' {
  declare module.exports: any;
}

declare module 'mobx-remotedev/lib/index' {
  declare module.exports: any;
}

declare module 'mobx-remotedev/lib/monitorActions' {
  declare module.exports: any;
}

declare module 'mobx-remotedev/lib/spy' {
  declare module.exports: any;
}

declare module 'mobx-remotedev/lib/utils' {
  declare module.exports: any;
}

declare module 'mobx-remotedev/src/dev' {
  declare module.exports: any;
}

declare module 'mobx-remotedev/src/filters' {
  declare module.exports: any;
}

declare module 'mobx-remotedev/src/getDecorator' {
  declare module.exports: any;
}

declare module 'mobx-remotedev/src/index' {
  declare module.exports: any;
}

declare module 'mobx-remotedev/src/monitorActions' {
  declare module.exports: any;
}

declare module 'mobx-remotedev/src/spy' {
  declare module.exports: any;
}

declare module 'mobx-remotedev/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mobx-remotedev/dist/mobx-remotedev.js' {
  declare module.exports: $Exports<'mobx-remotedev/dist/mobx-remotedev'>;
}
declare module 'mobx-remotedev/dist/mobx-remotedev.min.js' {
  declare module.exports: $Exports<'mobx-remotedev/dist/mobx-remotedev.min'>;
}
declare module 'mobx-remotedev/lib/dev.js' {
  declare module.exports: $Exports<'mobx-remotedev/lib/dev'>;
}
declare module 'mobx-remotedev/lib/filters.js' {
  declare module.exports: $Exports<'mobx-remotedev/lib/filters'>;
}
declare module 'mobx-remotedev/lib/getDecorator.js' {
  declare module.exports: $Exports<'mobx-remotedev/lib/getDecorator'>;
}
declare module 'mobx-remotedev/lib/index.js' {
  declare module.exports: $Exports<'mobx-remotedev/lib/index'>;
}
declare module 'mobx-remotedev/lib/monitorActions.js' {
  declare module.exports: $Exports<'mobx-remotedev/lib/monitorActions'>;
}
declare module 'mobx-remotedev/lib/spy.js' {
  declare module.exports: $Exports<'mobx-remotedev/lib/spy'>;
}
declare module 'mobx-remotedev/lib/utils.js' {
  declare module.exports: $Exports<'mobx-remotedev/lib/utils'>;
}
declare module 'mobx-remotedev/src/dev.js' {
  declare module.exports: $Exports<'mobx-remotedev/src/dev'>;
}
declare module 'mobx-remotedev/src/filters.js' {
  declare module.exports: $Exports<'mobx-remotedev/src/filters'>;
}
declare module 'mobx-remotedev/src/getDecorator.js' {
  declare module.exports: $Exports<'mobx-remotedev/src/getDecorator'>;
}
declare module 'mobx-remotedev/src/index.js' {
  declare module.exports: $Exports<'mobx-remotedev/src/index'>;
}
declare module 'mobx-remotedev/src/monitorActions.js' {
  declare module.exports: $Exports<'mobx-remotedev/src/monitorActions'>;
}
declare module 'mobx-remotedev/src/spy.js' {
  declare module.exports: $Exports<'mobx-remotedev/src/spy'>;
}
declare module 'mobx-remotedev/src/utils.js' {
  declare module.exports: $Exports<'mobx-remotedev/src/utils'>;
}
