// flow-typed signature: be35133f2b41197d3e392cb2d8b60455
// flow-typed version: <<STUB>>/purifycss-webpack-plugin_v^2.0.3/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'purifycss-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'purifycss-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'purifycss-webpack-plugin/index' {
  declare module.exports: $Exports<'purifycss-webpack-plugin'>;
}
declare module 'purifycss-webpack-plugin/index.js' {
  declare module.exports: $Exports<'purifycss-webpack-plugin'>;
}
