// flow-typed signature: 0b79b1926ab6234278e8e403c4a7cab8
// flow-typed version: <<STUB>>/scandir_v^0.1.2/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'scandir'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'scandir' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'scandir/example/basic' {
  declare module.exports: any;
}

declare module 'scandir/lib/iplugin' {
  declare module.exports: any;
}

declare module 'scandir/lib/libutil' {
  declare module.exports: any;
}

declare module 'scandir/lib/plugins/delete' {
  declare module.exports: any;
}

declare module 'scandir/lib/plugins/mv' {
  declare module.exports: any;
}

declare module 'scandir/lib/plugins/video/vlc-convert' {
  declare module.exports: any;
}

declare module 'scandir/lib/reporter/cli' {
  declare module.exports: any;
}

declare module 'scandir/lib/reporter/json' {
  declare module.exports: any;
}

declare module 'scandir/lib/reporter/unittest' {
  declare module.exports: any;
}

declare module 'scandir/lib/scandir-app' {
  declare module.exports: any;
}

declare module 'scandir/lib/scandir' {
  declare module.exports: any;
}

declare module 'scandir/test/test-bin' {
  declare module.exports: any;
}

declare module 'scandir/test/test-libutil' {
  declare module.exports: any;
}

// Filename aliases
declare module 'scandir/example/basic.js' {
  declare module.exports: $Exports<'scandir/example/basic'>;
}
declare module 'scandir/lib/iplugin.js' {
  declare module.exports: $Exports<'scandir/lib/iplugin'>;
}
declare module 'scandir/lib/libutil.js' {
  declare module.exports: $Exports<'scandir/lib/libutil'>;
}
declare module 'scandir/lib/plugins/delete.js' {
  declare module.exports: $Exports<'scandir/lib/plugins/delete'>;
}
declare module 'scandir/lib/plugins/mv.js' {
  declare module.exports: $Exports<'scandir/lib/plugins/mv'>;
}
declare module 'scandir/lib/plugins/video/vlc-convert.js' {
  declare module.exports: $Exports<'scandir/lib/plugins/video/vlc-convert'>;
}
declare module 'scandir/lib/reporter/cli.js' {
  declare module.exports: $Exports<'scandir/lib/reporter/cli'>;
}
declare module 'scandir/lib/reporter/json.js' {
  declare module.exports: $Exports<'scandir/lib/reporter/json'>;
}
declare module 'scandir/lib/reporter/unittest.js' {
  declare module.exports: $Exports<'scandir/lib/reporter/unittest'>;
}
declare module 'scandir/lib/scandir-app.js' {
  declare module.exports: $Exports<'scandir/lib/scandir-app'>;
}
declare module 'scandir/lib/scandir.js' {
  declare module.exports: $Exports<'scandir/lib/scandir'>;
}
declare module 'scandir/test/test-bin.js' {
  declare module.exports: $Exports<'scandir/test/test-bin'>;
}
declare module 'scandir/test/test-libutil.js' {
  declare module.exports: $Exports<'scandir/test/test-libutil'>;
}
