// flow-typed signature: 0f9904312fa4232c641ddafe91a5173f
// flow-typed version: <<STUB>>/tcomb-forked_v^3.4.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tcomb-forked'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'tcomb-forked' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tcomb-forked/lib/Any' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/Array' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/assert' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/assign' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/Boolean' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/create' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/Date' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/declare' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/decompose' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/dict' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/enums' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/Error' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/extend' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/fail' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/forbidNewOperator' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/fromJSON' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/func' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/Function' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/getDefaultInterfaceName' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/getFunctionName' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/getTypeName' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/installTypeFormatter' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/Integer' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/interface' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/intersection' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/irreducible' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/is' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/isArray' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/isBoolean' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/isFunction' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/isIdentity' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/isInterface' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/isMaybe' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/isNil' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/isNumber' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/isObject' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/isString' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/isStruct' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/isSubsetOf' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/isThenable' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/isType' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/isTypeName' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/isUnion' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/list' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/match' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/maybe' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/mixin' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/Nil' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/Number' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/Object' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/refinement' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/RegExp' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/String' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/stringify' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/struct' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/Thenable' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/tuple' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/Type' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/union' {
  declare module.exports: any;
}

declare module 'tcomb-forked/lib/update' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tcomb-forked/index' {
  declare module.exports: $Exports<'tcomb-forked'>;
}
declare module 'tcomb-forked/index.js' {
  declare module.exports: $Exports<'tcomb-forked'>;
}
declare module 'tcomb-forked/lib/Any.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/Any'>;
}
declare module 'tcomb-forked/lib/Array.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/Array'>;
}
declare module 'tcomb-forked/lib/assert.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/assert'>;
}
declare module 'tcomb-forked/lib/assign.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/assign'>;
}
declare module 'tcomb-forked/lib/Boolean.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/Boolean'>;
}
declare module 'tcomb-forked/lib/create.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/create'>;
}
declare module 'tcomb-forked/lib/Date.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/Date'>;
}
declare module 'tcomb-forked/lib/declare.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/declare'>;
}
declare module 'tcomb-forked/lib/decompose.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/decompose'>;
}
declare module 'tcomb-forked/lib/dict.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/dict'>;
}
declare module 'tcomb-forked/lib/enums.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/enums'>;
}
declare module 'tcomb-forked/lib/Error.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/Error'>;
}
declare module 'tcomb-forked/lib/extend.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/extend'>;
}
declare module 'tcomb-forked/lib/fail.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/fail'>;
}
declare module 'tcomb-forked/lib/forbidNewOperator.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/forbidNewOperator'>;
}
declare module 'tcomb-forked/lib/fromJSON.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/fromJSON'>;
}
declare module 'tcomb-forked/lib/func.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/func'>;
}
declare module 'tcomb-forked/lib/Function.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/Function'>;
}
declare module 'tcomb-forked/lib/getDefaultInterfaceName.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/getDefaultInterfaceName'>;
}
declare module 'tcomb-forked/lib/getFunctionName.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/getFunctionName'>;
}
declare module 'tcomb-forked/lib/getTypeName.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/getTypeName'>;
}
declare module 'tcomb-forked/lib/installTypeFormatter.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/installTypeFormatter'>;
}
declare module 'tcomb-forked/lib/Integer.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/Integer'>;
}
declare module 'tcomb-forked/lib/interface.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/interface'>;
}
declare module 'tcomb-forked/lib/intersection.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/intersection'>;
}
declare module 'tcomb-forked/lib/irreducible.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/irreducible'>;
}
declare module 'tcomb-forked/lib/is.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/is'>;
}
declare module 'tcomb-forked/lib/isArray.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/isArray'>;
}
declare module 'tcomb-forked/lib/isBoolean.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/isBoolean'>;
}
declare module 'tcomb-forked/lib/isFunction.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/isFunction'>;
}
declare module 'tcomb-forked/lib/isIdentity.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/isIdentity'>;
}
declare module 'tcomb-forked/lib/isInterface.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/isInterface'>;
}
declare module 'tcomb-forked/lib/isMaybe.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/isMaybe'>;
}
declare module 'tcomb-forked/lib/isNil.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/isNil'>;
}
declare module 'tcomb-forked/lib/isNumber.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/isNumber'>;
}
declare module 'tcomb-forked/lib/isObject.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/isObject'>;
}
declare module 'tcomb-forked/lib/isString.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/isString'>;
}
declare module 'tcomb-forked/lib/isStruct.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/isStruct'>;
}
declare module 'tcomb-forked/lib/isSubsetOf.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/isSubsetOf'>;
}
declare module 'tcomb-forked/lib/isThenable.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/isThenable'>;
}
declare module 'tcomb-forked/lib/isType.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/isType'>;
}
declare module 'tcomb-forked/lib/isTypeName.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/isTypeName'>;
}
declare module 'tcomb-forked/lib/isUnion.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/isUnion'>;
}
declare module 'tcomb-forked/lib/list.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/list'>;
}
declare module 'tcomb-forked/lib/match.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/match'>;
}
declare module 'tcomb-forked/lib/maybe.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/maybe'>;
}
declare module 'tcomb-forked/lib/mixin.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/mixin'>;
}
declare module 'tcomb-forked/lib/Nil.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/Nil'>;
}
declare module 'tcomb-forked/lib/Number.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/Number'>;
}
declare module 'tcomb-forked/lib/Object.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/Object'>;
}
declare module 'tcomb-forked/lib/refinement.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/refinement'>;
}
declare module 'tcomb-forked/lib/RegExp.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/RegExp'>;
}
declare module 'tcomb-forked/lib/String.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/String'>;
}
declare module 'tcomb-forked/lib/stringify.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/stringify'>;
}
declare module 'tcomb-forked/lib/struct.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/struct'>;
}
declare module 'tcomb-forked/lib/Thenable.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/Thenable'>;
}
declare module 'tcomb-forked/lib/tuple.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/tuple'>;
}
declare module 'tcomb-forked/lib/Type.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/Type'>;
}
declare module 'tcomb-forked/lib/union.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/union'>;
}
declare module 'tcomb-forked/lib/update.js' {
  declare module.exports: $Exports<'tcomb-forked/lib/update'>;
}
