// flow-typed signature: 1001f7575c4c5687398692ee0ac8cd83
// flow-typed version: <<STUB>>/testdom_v^2.0.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'testdom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'testdom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'testdom/test/spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'testdom/index' {
  declare module.exports: $Exports<'testdom'>;
}
declare module 'testdom/index.js' {
  declare module.exports: $Exports<'testdom'>;
}
declare module 'testdom/test/spec.js' {
  declare module.exports: $Exports<'testdom/test/spec'>;
}
