// flow-typed signature: 8c000af369c8562e07f39243a8d5d384
// flow-typed version: <<STUB>>/webpack-shell-plugin_v^0.5.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-shell-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-shell-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-shell-plugin/lib/index' {
  declare module.exports: any;
}

declare module 'webpack-shell-plugin/rollup.config' {
  declare module.exports: any;
}

declare module 'webpack-shell-plugin/src/webpack-shell-plugin' {
  declare module.exports: any;
}

declare module 'webpack-shell-plugin/test' {
  declare module.exports: any;
}

declare module 'webpack-shell-plugin/test/content' {
  declare module.exports: any;
}

declare module 'webpack-shell-plugin/test/entry' {
  declare module.exports: any;
}

declare module 'webpack-shell-plugin/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-shell-plugin/lib/index.js' {
  declare module.exports: $Exports<'webpack-shell-plugin/lib/index'>;
}
declare module 'webpack-shell-plugin/rollup.config.js' {
  declare module.exports: $Exports<'webpack-shell-plugin/rollup.config'>;
}
declare module 'webpack-shell-plugin/src/webpack-shell-plugin.js' {
  declare module.exports: $Exports<'webpack-shell-plugin/src/webpack-shell-plugin'>;
}
declare module 'webpack-shell-plugin/test.js' {
  declare module.exports: $Exports<'webpack-shell-plugin/test'>;
}
declare module 'webpack-shell-plugin/test/content.js' {
  declare module.exports: $Exports<'webpack-shell-plugin/test/content'>;
}
declare module 'webpack-shell-plugin/test/entry.js' {
  declare module.exports: $Exports<'webpack-shell-plugin/test/entry'>;
}
declare module 'webpack-shell-plugin/webpack.config.js' {
  declare module.exports: $Exports<'webpack-shell-plugin/webpack.config'>;
}
