// flow-typed signature: 03a2fb1ed467174d3e53185025a85a61
// flow-typed version: <<STUB>>/@material/button_v^0.1.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/button'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/button' {
  declare module.exports: any;
}
