// flow-typed signature: 3ea8700ca77c90a54afd46cfe6131c28
// flow-typed version: <<STUB>>/@material/button_v^0.1.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/button'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/button' {
  declare module.exports: any;
}
