// flow-typed signature: e94b5a112f9cc0995fff73bcaef1d9fc
// flow-typed version: <<STUB>>/@material/card_v^0.1.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/card'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/card' {
  declare module.exports: any;
}
