// flow-typed signature: 18ab9e0cad57665fd2379f3882e58b41
// flow-typed version: <<STUB>>/@material/form-field_v^0.1.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/form-field'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/form-field' {
  declare module.exports: any;
}
